import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  scrollContent: {
    flexGrow: 1,
    padding: 20,
    paddingBottom: 80,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 40,
  },
  headerTitle: { fontSize: 22, fontWeight: "700", color: "#1F2937" },
  configButton: { padding: 8 },
  userCard: {
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    padding: 15,
    marginTop: 20,
  },
  userInfo: { flexDirection: "row", alignItems: "center" },
  profileImage: { width: 60, height: 60, borderRadius: 30 },
  profileIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#E5E7EB",
    justifyContent: "center",
    alignItems: "center",
  },
  userDetails: { marginLeft: 15 },
  userName: { fontSize: 18, fontWeight: "600", color: "#111827" },
  userEmail: { fontSize: 14, color: "#6B7280" },
  section: { marginTop: 30 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 10,
    color: "#374151",
  },
  paymentCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    padding: 12,
    borderRadius: 10,
    justifyContent: "space-between",
  },
  paymentText: { flex: 1, marginLeft: 10, color: "#1F2937", fontSize: 15 },
  planCard: { backgroundColor: "#F9FAFB", padding: 15, borderRadius: 12 },
  planHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  planName: { fontSize: 16, fontWeight: "700", color: "#111827" },
  manageButton: { backgroundColor: "#E5E7EB", padding: 6, borderRadius: 6 },
  manageButtonText: { color: "#374151", fontSize: 13 },
  planPrice: { fontSize: 16, color: "#4B5563", marginTop: 5 },
  planDetails: { fontSize: 14, color: "#6B7280", marginTop: 3 },
  planActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  menuItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  menuItemLeft: { flexDirection: "row", alignItems: "center" },
  menuItemText: { fontSize: 15, marginLeft: 10, color: "#374151" },
  logoutItem: { marginTop: 10 },
  logoutText: { color: "#EF4444" },
  bottomSpacer: { height: 30 },
});
